# ~/growpromise-project/docker-compose.yml
version: '3.8'

services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: api-server-growpromise
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./api-server/uploads:/app/uploads
    networks:
      - growpromise-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: postgres-growpromise
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - growpromise-network

  redis:
    image: redis:7-alpine
    container_name: redis-growpromise
    restart: always
    networks:
      - growpromise-network
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  growpromise-network:
    external: true