version: '3.8'

services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api-server-growpromise
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: growpromise-network