version: '3.8'

services:
  nginx-ssl:
    image: nginx:alpine
    container_name: nginx-ssl-growpromise
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - growpromise-network
  
  certbot:
    image: certbot/certbot
    container_name: certbot-growpromise
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  growpromise-network:
    external: true
